export type PriceInfo = {
  title: string;
  price: string;
  description: string;
  features: string[];
};

export const priceTiers = ["Primitive", "Civilized", "Futuristic"] as const;
export type PriceTier = (typeof priceTiers)[number];

export const jobTypes = [
  "WebDeveloper",
  "SoftwareDeveloper",
  "GraphicDesigner",
  "Tutor",
] as const;
export type JobType = (typeof jobTypes)[number];

// TODO: Generated by github copilot, needs to be modified.
export const prices: {
  [key in JobType]: {
    [key in PriceTier]: PriceInfo;
  };
} = {
  WebDeveloper: {
    Primitive: {
      title: "One Page Website",
      price: "$400 \u2013 $800",
      description: "A single page website for your personal or business needs.",
      features: ["1 page", "No animations", "No backend"],
    },
    Civilized: {
      title: "Small Website",
      price: "$1000 \u2013 $4000",
      description: "A small website for your personal or business needs.",
      features: ["Up to 5 pages", "Basic animations", "Basic backend"],
    },
    Futuristic: {
      title: "Full Website",
      price: "$6000 \u2013 $10000",
      description: "A large website for your personal or business needs.",
      features: ["Up to 10 pages", "Advanced animations", "Advanced backend"],
    },
  },
  SoftwareDeveloper: {
    // Still need to do these.
    Primitive: {
      title: "Mini Application",
      price: "$500 \u2013 $1000",
      description: "A simple, single paged application.",
      features: [
        "1 page",
        "Simple UI",
        "No revisions",
        "Source code not included",
      ],
    },
    Civilized: {
      title: "Small Application",
      price: "$1200 \u2013 $4000",
      description: "A small application with multiple pages and features.",
      features: [
        "Up to 3 pages",
        "Basic UI",
        "Basic database",
        "Up to 3 revisions",
        "Source code included",
      ],
    },
    Futuristic: {
      title: "",
      price: "$5000 \u2013 $10000",
      description: "A futuristic software for your business.",
      features: [
        "Up to 5 pages",
        "Advanced UI",
        "Advanced database",
        "File System",
        "Several Revisions",
        "Source code included",
      ],
    },
  },
  GraphicDesigner: {
    Primitive: {
      title: "Photo Editing",
      price: "$50 \u2013 $300",
      description: "A primitive design for your business.",
      features: ["1 design", "No revisions", "No source files"],
    },
    Civilized: {
      title: "Vector Logo",
      price: "$200 \u2013 $800",
      description: "A civilized design for your business.",
      features: ["Up to 3 designs", "1 revision", "Source files included"],
    },
    Futuristic: {
      title: "Vector Drawing",
      price: "$1000 \u2013 $5000",
      description: "A futuristic design for your business.",
      features: ["Up to 5 designs", "3 revisions", "Source files included"],
    },
  },
  Tutor: {
    // Modify descriptions.
    Primitive: {
      title: "Elementary",
      price: "$20 \u2013 $30/hour",
      description: "Elementary school tutoring session.",
      features: [
        "First session free",
        "1 hour session",
        "Elementary school subjects",
        "Reduced rates for multiple children",
      ],
    },
    Civilized: {
      title: "High School",
      price: "$30 \u2013 $40/hour",
      description: "High school tutoring session.",
      features: [
        "First session half priced",
        "1 hour session",
        "High school subjects",
        "Reduced rates for groups",
      ],
    },
    Futuristic: {
      title: "University",
      price: "$40 \u2013 $60/hour",
      description: "College or University tutoring session.",
      features: [
        "First session half priced",
        "1 hour session",
        "Materials provided",
        "Customized curriculum",
      ],
    },
  },
};
