export type PriceInfo = {
  title: string;
  price: string;
  description: string;
  features: string[];
};

export const priceTiers = ["Primitive", "Civilized", "Futuristic"] as const;
export type PriceTier = (typeof priceTiers)[number];

export const jobTypes = [
  "WebDeveloper",
  "SoftwareDeveloper",
  "GraphicDesigner",
  "Tutor",
] as const;
export type JobTypes = (typeof jobTypes)[number];

// TODO: Generated by github copilot, needs to be modified.
export const prices: {
  [key in JobTypes]: {
    [key in PriceTier]: PriceInfo;
  };
} = {
  WebDeveloper: {
    Primitive: {
      title: "Web Developer - Primitive",
      price: "$100",
      description: "A primitive website for your business",
      features: ["1 page", "No animations", "No backend"],
    },
    Civilized: {
      title: "Web Developer - Civilized",
      price: "$500",
      description: "A civilized website for your business",
      features: ["Up to 5 pages", "Basic animations", "Basic backend"],
    },
    Futuristic: {
      title: "Web Developer - Futuristic",
      price: "$1000",
      description: "A futuristic website for your business",
      features: ["Up to 10 pages", "Advanced animations", "Advanced backend"],
    },
  },
  SoftwareDeveloper: {
    Primitive: {
      title: "Software Developer - Primitive",
      price: "$500",
      description: "A primitive software for your business",
      features: ["1 feature", "No UI", "No database"],
    },
    Civilized: {
      title: "Software Developer - Civilized",
      price: "$2000",
      description: "A civilized software for your business",
      features: ["Up to 5 features", "Basic UI", "Basic database"],
    },
    Futuristic: {
      title: "Software Developer - Futuristic",
      price: "$5000",
      description: "A futuristic software for your business",
      features: ["Up to 10 features", "Advanced UI", "Advanced database"],
    },
  },
  GraphicDesigner: {
    Primitive: {
      title: "Graphic Designer - Primitive",
      price: "$50",
      description: "A primitive design for your business",
      features: ["1 design", "No revisions", "No source files"],
    },
    Civilized: {
      title: "Graphic Designer - Civilized",
      price: "$200",
      description: "A civilized design for your business",
      features: ["Up to 3 designs", "1 revision", "Source files included"],
    },
    Futuristic: {
      title: "Graphic Designer - Futuristic",
      price: "$500",
      description: "A futuristic design for your business",
      features: ["Up to 5 designs", "3 revisions", "Source files included"],
    },
  },
  Tutor: {
    Primitive: {
      title: "Tutor - Primitive",
      price: "$20/hour",
      description: "A primitive tutoring session for your needs",
      features: ["1 hour session", "No materials provided"],
    },
    Civilized: {
      title: "Tutor - Civilized",
      price: "$50/hour",
      description: "A civilized tutoring session for your needs",
      features: ["1 hour session", "Materials provided"],
    },
    Futuristic: {
      title: "Tutor - Futuristic",
      price: "$100/hour",
      description: "A futuristic tutoring session for your needs",
      features: [
        "1 hour session",
        "Materials provided",
        "Customized curriculum",
      ],
    },
  },
};
